// export const USER_API_END_POINT = "https://taskify-api-zn2a.onrender.com/api/user"
// export const TASK_API_END_POINT = "https://taskify-api-zn2a.onrender.com/api/task"
// export const BASE_URL ="https://taskify-api-zn2a.onrender.com/api"
export const USER_API_END_POINT = "http://localhost:3000/api/user"
export const TASK_API_END_POINT = "http://localhost:3000/api/task"
export const BASE_URL ="http://localhost:3000/api"